### ISSUE TITLE
Flag Quiz Leaderboard is ugly

### ISSUE THREAD

**Issue by LevaniVashadze** [LewisProjects/Ogiroid#26]
![image](https://user-images.githubusercontent.com/100613979/183247481-b7103dcf-0cd0-4c33-beb1-d582d3474238.png)
This is how it looks
I tried using prettytable didn't work  out

**Comment by TrueWLAN** [comment]
@LevaniVashadze then don't use mobile

**Comment by LevaniVashadze** [comment]
yeah i dont use it often but i create the bot for everyone.

**Comment by ImmaHarry** [comment]
am closing this, came up with a minor fix anyhow.
