### ISSUE TITLE
Do you think an urban dictionary command is okay?

### ISSUE THREAD

**Issue by ImmaHarry** [LewisProjects/Ogiroid#33]
![image](https://user-images.githubusercontent.com/62475932/184371024-b5340c5a-bde5-45cd-a004-ce2ab7a58703.png)
![image](https://user-images.githubusercontent.com/62475932/184371431-db9d756c-4ae5-436e-a596-81bf55324ee8.png)
As you can see, their definitions are **very unmoderated**, get what I am saying?
They can be on extreme ends, as shown in the image. So do you think we should implement this?

**Comment by ImmaHarry** [comment]
![image](https://user-images.githubusercontent.com/62475932/184372711-4503e47f-31b2-48e7-85f3-47ba77e91525.png)
Another example 💀

**Comment by LevaniVashadze** [comment]
💀

**Comment by LevaniVashadze** [comment]
maybe use the nsfw filter from edoC and run a function on the content and don't send the answer if it is NSFW

**Comment by LevaniVashadze** [comment]
but tbh I doubt people would be trying to abuse it

**Comment by JasonLovesDoggo** [comment]
> but tbh I doubt people would be trying to abuse it
> 
> 
> 

That's not the problem The problem is because this contains potentially "racially intensive" and other such words that could get discord to revoke or deny the server from a community service status

**Comment by LevaniVashadze** [comment]
thats why we could check ourselves if it contains nsfw and if it does deny sending it

**Comment by JasonLovesDoggo** [comment]
> ![image](https://user-images.githubusercontent.com/62475932/184371024-b5340c5a-bde5-45cd-a004-ce2ab7a58703.png)
> ![image](https://user-images.githubusercontent.com/62475932/184371431-db9d756c-4ae5-436e-a596-81bf55324ee8.png)
> As you can see, their definitions are **very unmoderated**, get what I am saying?
> They can be on extreme ends, as shown in the image. So do you think we should implement this?
> 

I would say add a @commands.is_nsfw() check to only allow this command to be run in nsfw channela

**Comment by LevaniVashadze** [comment]
yeah but many people cant access nsfw channels so it would be easier if we check on our sides for any words

**Comment by ImmaHarry** [comment]
> yeah but many people cant access nsfw channels so it would be easier if we check on our sides for any words

We have no NSFW channels lolol

**Comment by LevaniVashadze** [comment]
yet no but i heard people saying they cant access them

**Comment by JasonLovesDoggo** [comment]
> yeah but many people cant access nsfw channels so it would be easier if we check on our sides for any words

1. Somebody who has had the unfortunate experience of working with NSFW filters and checkers before trust me it's not easy or fun.
2. Maybe the people who can't access NSFW channels SHOULDN'T be able to use that command.

**Comment by LevaniVashadze** [comment]
tbh at the end of the day if someone doesn't know a definition they will just be able /google it so its not the most needed command

**Comment by ImmaHarry** [comment]
Let's hold onto this command for a while then.
