### ISSUE TITLE
intermittent bug

### ISSUE THREAD

**Issue by LevaniVashadze** [LewisProjects/Ogiroid#66]
disnake.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: User(guild_id=985234686878023730, user_id=963860161976467498, lvl=14, xp=1851) is not in list

error looks like this usually happens after using /set_lvl and I think it has to do with cache not updating quickly enough

**Comment by JasonLovesDoggo** [comment]
Simple fix

**Comment by JasonLovesDoggo** [comment]
reopen if occurs again after fix is in prod
